# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build-the-book

jobs:
  build-the-book:
    runs-on: ubuntu-latest
    container: 
      image: rocker/r2u:latest
    name: ubuntu-latest (release)

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Quarto
        run: |
          apt-get update -qq
          apt-get install -y curl
          curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
          dpkg -i quarto-linux-amd64.deb

      - name: Restore R packages with renv
        run: |
          R -e "renv::restore()"

      - run: quarto render
      